
package turismouy.svcentral.middlewares.interfaces;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonitoreoWebService", targetNamespace = "http://interfaces.middlewares.svcentral.turismouy/", wsdlLocation = "http://localhost:5000/API/Monitoreo?wsdl")
public class MonitoreoWebService
    extends Service
{

    private final static URL MONITOREOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONITOREOWEBSERVICE_EXCEPTION;
    private final static QName MONITOREOWEBSERVICE_QNAME = new QName("http://interfaces.middlewares.svcentral.turismouy/", "MonitoreoWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5000/API/Monitoreo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONITOREOWEBSERVICE_WSDL_LOCATION = url;
        MONITOREOWEBSERVICE_EXCEPTION = e;
    }

    public MonitoreoWebService() {
        super(__getWsdlLocation(), MONITOREOWEBSERVICE_QNAME);
    }

    public MonitoreoWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONITOREOWEBSERVICE_QNAME, features);
    }

    public MonitoreoWebService(URL wsdlLocation) {
        super(wsdlLocation, MONITOREOWEBSERVICE_QNAME);
    }

    public MonitoreoWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONITOREOWEBSERVICE_QNAME, features);
    }

    public MonitoreoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitoreoWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MonitoreoWeb
     */
    @WebEndpoint(name = "MonitoreoWebPort")
    public MonitoreoWeb getMonitoreoWebPort() {
        return super.getPort(new QName("http://interfaces.middlewares.svcentral.turismouy/", "MonitoreoWebPort"), MonitoreoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitoreoWeb
     */
    @WebEndpoint(name = "MonitoreoWebPort")
    public MonitoreoWeb getMonitoreoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interfaces.middlewares.svcentral.turismouy/", "MonitoreoWebPort"), MonitoreoWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONITOREOWEBSERVICE_EXCEPTION!= null) {
            throw MONITOREOWEBSERVICE_EXCEPTION;
        }
        return MONITOREOWEBSERVICE_WSDL_LOCATION;
    }

}
