
package turismouy.svcentral.middlewares.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonitoreoWeb", targetNamespace = "http://interfaces.middlewares.svcentral.turismouy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonitoreoWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saludo", targetNamespace = "http://interfaces.middlewares.svcentral.turismouy/", className = "turismouy.svcentral.middlewares.interfaces.Saludo")
    @ResponseWrapper(localName = "saludoResponse", targetNamespace = "http://interfaces.middlewares.svcentral.turismouy/", className = "turismouy.svcentral.middlewares.interfaces.SaludoResponse")
    @Action(input = "http://interfaces.middlewares.svcentral.turismouy/MonitoreoWeb/saludoRequest", output = "http://interfaces.middlewares.svcentral.turismouy/MonitoreoWeb/saludoResponse")
    public String saludo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saludoGeneral", targetNamespace = "http://interfaces.middlewares.svcentral.turismouy/", className = "turismouy.svcentral.middlewares.interfaces.SaludoGeneral")
    @ResponseWrapper(localName = "saludoGeneralResponse", targetNamespace = "http://interfaces.middlewares.svcentral.turismouy/", className = "turismouy.svcentral.middlewares.interfaces.SaludoGeneralResponse")
    @Action(input = "http://interfaces.middlewares.svcentral.turismouy/MonitoreoWeb/saludoGeneralRequest", output = "http://interfaces.middlewares.svcentral.turismouy/MonitoreoWeb/saludoGeneralResponse")
    public String saludoGeneral();

}
