
package turismouy.svcentral.middlewares.controladores;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HoraWebService", targetNamespace = "http://controladores.middlewares.svcentral.turismouy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HoraWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerHoraActual", targetNamespace = "http://controladores.middlewares.svcentral.turismouy/", className = "turismouy.svcentral.middlewares.controladores.ObtenerHoraActual")
    @ResponseWrapper(localName = "obtenerHoraActualResponse", targetNamespace = "http://controladores.middlewares.svcentral.turismouy/", className = "turismouy.svcentral.middlewares.controladores.ObtenerHoraActualResponse")
    @Action(input = "http://controladores.middlewares.svcentral.turismouy/HoraWebService/obtenerHoraActualRequest", output = "http://controladores.middlewares.svcentral.turismouy/HoraWebService/obtenerHoraActualResponse")
    public String obtenerHoraActual();

}
