
package turismouy.svcentral.middlewares.controladores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HoraWebServiceService", targetNamespace = "http://controladores.middlewares.svcentral.turismouy/", wsdlLocation = "http://localhost:5000/API/HoraWebService?wsdl")
public class HoraWebServiceService
    extends Service
{

    private final static URL HORAWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HORAWEBSERVICESERVICE_EXCEPTION;
    private final static QName HORAWEBSERVICESERVICE_QNAME = new QName("http://controladores.middlewares.svcentral.turismouy/", "HoraWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5000/API/HoraWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HORAWEBSERVICESERVICE_WSDL_LOCATION = url;
        HORAWEBSERVICESERVICE_EXCEPTION = e;
    }

    public HoraWebServiceService() {
        super(__getWsdlLocation(), HORAWEBSERVICESERVICE_QNAME);
    }

    public HoraWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HORAWEBSERVICESERVICE_QNAME, features);
    }

    public HoraWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, HORAWEBSERVICESERVICE_QNAME);
    }

    public HoraWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HORAWEBSERVICESERVICE_QNAME, features);
    }

    public HoraWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HoraWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HoraWebService
     */
    @WebEndpoint(name = "HoraWebServicePort")
    public HoraWebService getHoraWebServicePort() {
        return super.getPort(new QName("http://controladores.middlewares.svcentral.turismouy/", "HoraWebServicePort"), HoraWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HoraWebService
     */
    @WebEndpoint(name = "HoraWebServicePort")
    public HoraWebService getHoraWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controladores.middlewares.svcentral.turismouy/", "HoraWebServicePort"), HoraWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HORAWEBSERVICESERVICE_EXCEPTION!= null) {
            throw HORAWEBSERVICESERVICE_EXCEPTION;
        }
        return HORAWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
